### ISSUE TITLE
Projects listing page and individual film details page

### ISSUE THREAD

**Issue by RadhikaPPatel** [Uprising-Global/buildly-react-template#2]
### Purpose

1. Create a new Projects listing page as per the design.
2. Create a new Individual film details page as per the design.

### Tasks

- [ ] Create UI for listing page.
- [ ] Integrate listing page with BE APIs.
- [ ] Create UI for individual details page.
- [ ] Integrate individual details page with BE APIs.
